### ISSUE TITLE
Вопросы на повышение баллов

### ISSUE THREAD

**Issue by igsha** [Anastasia76575/Anastasia_Lysakovskaia#8]
Каждый вопрос по 0.5 балла. Добрать до следующей оценки нужно 20 баллов, что соответствует ответам на любые 40 вопросов. Остальные вопросы нужны для подстраховки.
Там, где требуется программировать, можно для себя использовать http://coliru.stacked-crooked.com.
Документацию можно смотреть в https://cppreference.com.

1. Распишите лямбда-выражение `[i = 0](auto x) mutable { return x + i++; }` через функтор.
1. К какой категории относится итератор в алгоритме `std::reverse` (см. https://cppreference.com)?
1. Как называется конструктор, который вызывается из другого конструктора в том же классе?
1. Как называется конструктор у класса `A`, сигнатрура которого `A(A&&)`?
1. К какому паттерну проектирования относится лабораторная работа №3?
1. Почему `int i = -1 >> 2;` равен -1, тогда как `int i = 1 >> 2;` равен 0?
1. Какой тип будет у переменной `auto i = -1 + 7u;`?
1. Соотнесите следующие ошибки по категориям: ошибка компиляции, ошибка линковки, ошибка исполнения
    1. `void func(ind i);` (опечатка в типе)
    1. в заголовочном файле есть сигнатура функции, но нигде нет кода её тела
    1. ошибка `SEGFAULT`
    1. `std::tuple<int, char> x = 4568.5;`
1. Как создать рекурсивный тип внутри `std::variant`?
1. Какие методы нужны у объекта `obj`, чтобы можно было его использовать в range-loop: `for (auto i : obj)`?
1. Как вызвать внутри шаблонной функции шаблонный метод класса?
1. Какой будет размер объекта `std::variant<int32_t, uint8_t, int16_t>` в терминах `sizeof`?
Т.е. `sizeof(std::variant<int32_t, uint8_t, int16_t>) == sizeof(?)`, выравнивания можно не учитывать.
1. Как при наследовании сказать компилятору, чтобы он использовал ("вытянул") конструкторы базового класса?
1. Как получить значение из варианта в примере?

    ```
    std::variant<int, double, char> v = 66.5;
    double value = ?
    ```

1. Как мне узнать, совпадает ли мой тип `T` с одним из типов `Ts...` из вариативного шаблона?
1. Какой алгоритм из STL подойдёт, чтобы инициализировать массив арифметической прогрессией с числа 42?
1. У меня есть некоторый шаблонный класс `range<T>`, у которого есть метод `const T& begin() const`.
Мне нужно реализовать метод `T& begin()`.
Как это сделать, переиспользовав константный метод `const T& begin() const`?
1. Как создать шаблонную переменную числа пи, чтобы можно было использовать `pi<float>`, `pi<double>` или даже `pi<int>`.
1. Как к объекту `std::variant<int, float> x` прибавить число 22?
1. Допустим, мы находимся в лябмда-функции `auto lambda = [](auto x) { ... }`.
Как создать переменную a в теле лямбды такого же типа, что и аргумент `x`?
1. Что больше: `double` или `uint64_t`?
1. Чем паттерн проектирования декоратор отличается от паттерна адаптора?
1. К какому типу относится паттерн проектирования синглтон (одиночка)?
1. Почему можно писать `std::vector v{{7, 8, 9, 10, 11}}` без указания типа `int`?
1. Как получить значение типа `double` из кортежа `std::tuple<int, double, char>`?
1. Как получить значения строки и стобца `(i, j)` из линейного индекса `index` у двумерного массива, зная только ширину `w`?
1. Что такое разыменование?
1. Какими операторами должен обладать итератор категории RandomAccess?
1. Как вывести в поток `std::cout` свой тип `Object` (какую функцию для этого нужно реализовать)?
1. Где может пригодиться приватное наследование?
1. Какой программой собираются проекты в лабораторных работах?
1. Какой стандарт языка С++ используется в лабораторных?
1. Какая библиотека boost используется в последней лабораторной для написания функции `make_strided_range`?
1. Как отправить закоммиченные изменения в текущей ветке на удалённый сервер?
1. Какой паттер проектирования использован для реализации [`std::vector<bool>::reference`](https://en.cppreference.com/w/cpp/container/vector_bool/reference)?
1. Как дождаться окончания работы объекта `std::thread`?
1. Для каких целей следует использовать библиотеку `boost::spirit::x3`?
1. Какая библиотека STL нужна для работы со временем?
1. Почему перед переменной может быть написано `constexpr`?
1. Чем можно заменить конструкцию `std::enable_if` при использовании стандарта С++17?
1. Чем `std::recursive_mutex` отличается от обычного `std::mutex`?
1. Как связаны `std::weak_ptr` и `std::shared_ptr`, что без чего не может работать?
1. `int x = func();` - то, что вернула `func`, - это prvalue, lvalue, rvalue или xvalue?

**Comment by yungstacy** [comment]
1. Эта лямбда будет эквивалентна такому функтору:
```cpp
struct Functor {
    template <typename T> 
    double operator()(const T x) const {
        return x + ++i;
    }   
    private:
        mutable double i = 0;
};

Functor functor;
```
2. [LegacyBidirectionalIterator](https://en.cppreference.com/w/cpp/named_req/BidirectionalIterator)
3. [Делегирующий конструктор](https://ravesli.com/urok-119-delegiruyushhie-konstruktory/).
4. [Перемещающий конструктор](https://en.cppreference.com/w/cpp/language/move_constructor).
5. Поведенческий паттерн [Iterator](https://refactoring.guru/ru/design-patterns/iterator)
6. -1 в двоичном коде это все единицы и так как сдвиг арифметический, то слева всегда будет появляться единица, и сколько бы мы не сдвигали его это будет -1, с 1 все наоборот при сдвиге будет слева появляться 0, и сколько бы мы не сдвигали наше число всегда будет 0.
7. `unsigned int`.
8. 1.`void func(ind i);` (опечатка в типе) - это ошибка компиляции.
    2. в заголовочном файле есть сигнатура функции, но нигде нет кода её тела - это ошибка линковки.
    3. ошибка `SEGFAULT`- это ошибка исполнения.
    4. `std::tuple<int, char> x = 4568.5;` - ошибка компиляции.
9. Пример из 4 лр: В нем можно рекурсивно укладывать `recursive_array2` за счет `boost::recursive_wrapper`, он нужен потому что без него, тип не соберется так он до конца не объявлен, а `boost::recursive_wrapper` алоцирует тип [динамически](https://www.boost.org/doc/libs/1_66_0/doc/html/boost/recursive_wrapper.html).
```cpp
struct recursive_array2
    : public std::vector<
        std::variant<
            number,
            boost::recursive_wrapper<recursive_array2>
        >
    > {
    using vector::vector;
};
```
10. begin() и end(), [range-based for loop](https://en.cppreference.com/w/cpp/language/range-for) будет инкрементировать то что вернет begin до тех пор пока не дойдет до end.
11. Не поняла вопроса, если явно указывать тип шаблона все работает [пример](http://coliru.stacked-crooked.com/a/8efa7a5740b1b203)
12. `std::variant<int32_t, uint8_t, int16_t>` в терминах sizeof будет занимать 8 байт, так как самый большой тип у нас это `int32_t`, а так же `variant` должен хранить тег текущего типа, выравнивание будет по 4, так как это `sizeof(int32_t)`, значит нам нужно 8 байт, `sizeof(std::variant<int32_t, uint8_t, int16_t>) == sizeof(std::variant<int32_t>)`.
13. [Использовать](https://en.cppreference.com/w/cpp/language/using_declaration) `using`, пример из 4 лр:
```cpp
struct number
    : public std::variant<
        int,
        float
    > {
    using variant::variant;
};
```
14. [Использовать](https://en.cppreference.com/w/cpp/utility/variant/get) `std::get` пример:
```cpp
std::variant<int, double, char> v = 66.5;
double value = std::get<double>(v);
```
15. Использовать функции:
    `std::disjunction_v` она берет логическое или от всего что внутри
    `std::is_same` она проверяет совпадение типов
пример из лр 4:
```cpp
template<typename T>
decltype(auto) as() const {
    if constexpr (std::disjunction_v<
        std::is_same<
            boost::recursive_wrapper<T>, variant_types_pack
        >...
    >) {
        return std::get<boost::recursive_wrapper<T>>(*this).get();
    } else {
        return std::get<T>(*this);
    }
}
```
16. Нам [нужен](https://en.cppreference.com/w/cpp/algorithm/iota) `std::iota` пример:
```cpp
std::list<int> l(10);
std::iota(l.begin(), l.end(), 42);
```
17. Нужно сначала перекастовать this в константу и вызвать константый метод, а потом кастануть обратно.
```cpp
T& begin() {
    return const_cast<T&>(const_cast<const range*>(this)->begin<T>());
}
```
18. Нужно использовать [variable template](https://en.cppreference.com/w/cpp/language/variable_template).
```cpp
template<class T>
constexpr T pi = T(3.1415926535897932385L);
```
19. Есть 3 способа, они описаны в [этой статье](https://habr.com/ru/post/415737/), реализую самый простой:
```cpp
std::variant<int, float> x;
x = std::visit([](auto&& arg) -> std::variant<int, float> {return arg + 22;}, v);
```
20. Нужно использовать `decltype(x)`
21. Зависит от компилятора, так как размер `double` не указан в стандарте с++, он обычно подчиняется [этому стандарту](https://en.wikipedia.org/wiki/IEEE_754), в обычных условиях они будут равны по 8 байт.
22. [Декоратор](https://refactoring.guru/ru/design-patterns/decorator) нужен для того, чтобы динамически добавлять новую функциональность в объекты, а [адаптер](https://refactoring.guru/ru/design-patterns/adapter) нужен для того, чтобы объекты с разными интерфейсами работали вместе.
23. [Singleton](https://refactoring.guru/ru/design-patterns/singleton) это пораждающий паттерн.
24. Это позволяет делать [Template argument deduction].(https://en.cppreference.com/w/cpp/language/template_argument_deduction) добавленный в c++17.
25. При [помощи](https://en.cppreference.com/w/cpp/utility/tuple/get) `std::get`:
```cpp
std::tuple<int, double, char> a;
std::cout << std::get<double>(a) << std::endl;
```
26. Нужно найти расстояния до `begin` это будет `d`, и тогда `i = d % w`, а `j = d / w`. 
27. Разыменование это получения значения из указателя.
28. [cppreference](https://en.cppreference.com/w/cpp/named_req/RandomAccessIterator) говорит о том, что необходимы:
- `+=`
- комутативный  `+`
- `-=`
- комутативный  `-`
- `>`
- `<`
- `>=`
- `<=`
- постфиксные и префиксные `++` и `--`
- `==`
- `*`
Предположу, что все сравнения в 20 стандарте можно будет заменить на космический корабль
29. Необходимо перегрузить соответствующую функцию:
```cpp
ostream& operator<<(ostream& os, const Object& dt);
```
30. Приватное наследование необходимо, когда мы не хотим, чтобы потомок как-то влиял на данные внутри базового класса, те потомок не сможет получить к ним доступ, все public и protected в потомке будут private.
31. [cmake](https://cmake.org/).
32. C++17.
33. `boost/range/adaptors.hpp` [документация](https://www.boost.org/doc/libs/1_72_0/libs/range/doc/html/range/reference/adaptors.html)
34. `git push origin master`, здесь origin это куда отправить, а master это какую ветку отправить.
35. это структурный патерн - Proxy
36. Необходимо [заджойнить](https://en.cppreference.com/w/cpp/thread/thread/join) поток к основному. 
```cpp
std::thread a(b);
a.join();
```
37. [Она](https://www.boost.org/doc/libs/1_75_0/libs/spirit/doc/x3/html/spirit_x3/introduction.html) используется для того, чтобы писать рекурсивные парсеры.
38. `chrono`, ее добавили с c++11. [Документация](https://en.cppreference.com/w/cpp/chrono).
39. [constexpr](https://en.cppreference.com/w/cpp/language/constexpr) нужен для того, чтобы объявить константу времени компиляции, чтобы использовать ее при метапрограммировании.
40. В с++17 можно использовать конструкцию `if constexpr` которая позволяет проверять условие во время компиляции, раньше для этого использовался `std::enable_if`, эта парадигма называлась SFINAE.
41. Если в рекурсивной функции использовать обычный `std::mutex`, то при входе он залочится и рекурсивная функция будет ждать саму себя, те будет deadlock, чтобы решить эту проблему, нужно использовать `std::recursive_mutex` он позволяет 1 и тому же потоку брать 1 и тот же мьютекс несколько раз.
42. `std::shared_ptr` это умный указатель, который создает объект в котором будет хранится счетчик ссылок на то, на что он указывает, а `std::weak_ptr` создает слабую связь к объекту которым управляет `std::shared_ptr`, поэтому  `std::weak_ptr` не может существовать без`std::shared_ptr`.
43. это будет prvalue, но я не очень хорошо понимаю разницу в этом, я не помню чтобы это было в лекциях, а если было, то нужно больше внимания обратить на это

**Comment by yungstacy** [comment]
@igsha  Посмотрите пожалуйста, некоторые вопросы были не совсем понятны, но я старалась ответить

**Comment by igsha** [comment]
Не хватает на оценку, исправьте замечания к вопросам

1\.  Здесь есть 2 ошибки, внимательно посмотрите на само выражение.
11\. Нужно связывание через аргумент: http://coliru.stacked-crooked.com/a/c8bea9606412e530
26\. Здесь есть ошибка, внимательно посмотрите на то, что такое строка и столбец.
28\. Не хватает ещё одной операции.
30\. Вообще-то это не так, посмотрите лабораторную №2

P.S.: 43. Вообще-то это было на лекции https://cvlabmiet.github.io/master-programming/lecture-7.html#(22) - Ваш ответ правильный.

**Comment by yungstacy** [comment]
1\. 1 ошибка это постфиксный инкремент, а 2 наверное в слове const.
```cpp
struct Functor {
    template <typename T> 
    double operator()(T x) const {
        return x + i++;
    }   
    private:
        mutable double i = 0;
};

Functor functor;
```
11\. Совсем забыла про ключевое слово `template`: [решение](http://coliru.stacked-crooked.com/a/0c188d4addf07fe9).
26\. Будет наоборот `j = d % w`, а `i = d / w`.
28\. Нам еще нужен convertible to reference, те `[]`.
30\. Суть лабораторной работы 2 была в том, что мы наследовались приватно от лок гварда, который лочил мьтекс в конструкторе и разлочивал в деструкторе, и как я и описала мы не можем получить доступ к непосредственно мьютексу, так как он для  нас стал private.

**Comment by yungstacy** [comment]
@igsha  Я переделала, посмотрите пожалуйста

**Comment by igsha** [comment]
1\. `i = 0` - это `int i = 0`, а не `double i = 0`. Было бы `i = 0.0`, тогда другое дело.
30\. Приватное наследование прячет методы базого класса _у_ наследника, а не _от_ наследника. Для прокси же конструктор лок гарда не спрятан. Это способ спрятать некоторый или весь интерфейс базового класса от пользователя.

Остальное верно. Распределю оценки по лабам ещё.

**Comment by yungstacy** [comment]
@igsha поняла, спасибо
